version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ergo-one-dev"
s3_bucket = "aws-sam-cli-deploy-ergo-one-dev"
s3_prefix = "ergo-one-dev"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
