AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
# More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
# More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
# Find out more about other implicit resources you can reference within SAM
# https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api

Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambdas/hello-world
      Handler: hello-world.lambdaHandler
      Runtime: nodejs12.x

      Events:
        HelloWorldEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /hello
            Method: get

  RootLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambdas/root
      Handler: root.lambdaHandler
      Runtime: nodejs12.x

      Events:
        RootEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /
            Method: get

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev

Outputs:
  BaseUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${ApiGateway.Stage}/"
